version: '3.8'

services:
  s3-edgedelta-streamer:
    build: .
    ports:
      - "8080:8080"  # Health check port
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./state.json:/app/state.json
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Mock EdgeDelta endpoint for testing
  edgedelta-mock:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    profiles:
      - testing